<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-02T15:32:18 SEČ" name="Suite" finished-at="2025-01-02T15:32:32 SEČ" duration-ms="13238">
    <groups>
    </groups>
    <test started-at="2025-01-02T15:32:18 SEČ" name="Test" finished-at="2025-01-02T15:32:32 SEČ" duration-ms="13238">
      <class name="com.parabank.parasoft.testCases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:18 SEČ" name="setup" finished-at="2025-01-02T15:32:23 SEČ" duration-ms="4187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_01_loginWithValidCredentials()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:23 SEČ" name="TC_01_loginWithValidCredentials" finished-at="2025-01-02T15:32:24 SEČ" duration-ms="962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_loginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:24 SEČ" name="tearDown" finished-at="2025-01-02T15:32:24 SEČ" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:24 SEČ" name="setup" finished-at="2025-01-02T15:32:26 SEČ" duration-ms="2887" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_02_loginUserWithInvalidUsername()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:26 SEČ" name="TC_02_loginUserWithInvalidUsername" finished-at="2025-01-02T15:32:27 SEČ" duration-ms="927" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Account login with invalid username should fail, but it succeeded expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Account login with invalid username should fail, but it succeeded expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.parabank.parasoft.testCases.LoginTest.TC_02_loginUserWithInvalidUsername(LoginTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_loginUserWithInvalidUsername -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:27 SEČ" name="tearDown" finished-at="2025-01-02T15:32:27 SEČ" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:27 SEČ" name="setup" finished-at="2025-01-02T15:32:30 SEČ" duration-ms="2669" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_03_loginUserWithInvalidPassword()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:30 SEČ" name="TC_03_loginUserWithInvalidPassword" finished-at="2025-01-02T15:32:32 SEČ" duration-ms="1561" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Account login with invalid password should fail, but it succeeded expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Account login with invalid password should fail, but it succeeded expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.parabank.parasoft.testCases.LoginTest.TC_03_loginUserWithInvalidPassword(LoginTest.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_loginUserWithInvalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@71d44a3]" started-at="2025-01-02T15:32:32 SEČ" name="tearDown" finished-at="2025-01-02T15:32:32 SEČ" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.parabank.parasoft.testCases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
