<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-02T15:50:43 SEČ" name="Default suite" finished-at="2025-01-02T15:50:59 SEČ" duration-ms="15607">
    <groups>
    </groups>
    <test started-at="2025-01-02T15:50:43 SEČ" name="Default test" finished-at="2025-01-02T15:50:59 SEČ" duration-ms="15607">
      <class name="com.parabank.parasoft.testCases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:43 SEČ" name="setup" finished-at="2025-01-02T15:50:47 SEČ" duration-ms="3587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_01_loginWithValidCredentials()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:47 SEČ" name="TC_01_loginWithValidCredentials" finished-at="2025-01-02T15:50:48 SEČ" duration-ms="982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_loginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:48 SEČ" name="tearDown" finished-at="2025-01-02T15:50:48 SEČ" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:48 SEČ" name="setup" finished-at="2025-01-02T15:50:51 SEČ" duration-ms="2916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_02_loginWithInvalidUsername()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:51 SEČ" name="TC_02_loginWithInvalidUsername" finished-at="2025-01-02T15:50:52 SEČ" duration-ms="944" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Account login with invalid username should fail, but it succeeded expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Account login with invalid username should fail, but it succeeded expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.parabank.parasoft.testCases.LoginTest.TC_02_loginWithInvalidUsername(LoginTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_loginWithInvalidUsername -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:52 SEČ" name="tearDown" finished-at="2025-01-02T15:50:52 SEČ" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:52 SEČ" name="setup" finished-at="2025-01-02T15:50:55 SEČ" duration-ms="2702" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_03_loginWithInvalidPassword()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:55 SEČ" name="TC_03_loginWithInvalidPassword" finished-at="2025-01-02T15:50:56 SEČ" duration-ms="987" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Account login with invalid password should fail, but it succeeded expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Account login with invalid password should fail, but it succeeded expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.parabank.parasoft.testCases.LoginTest.TC_03_loginWithInvalidPassword(LoginTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_loginWithInvalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:56 SEČ" name="tearDown" finished-at="2025-01-02T15:50:56 SEČ" duration-ms="110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:56 SEČ" name="setup" finished-at="2025-01-02T15:50:58 SEČ" duration-ms="2469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_04_loginWithEmptyCredentials()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:58 SEČ" name="TC_04_loginWithEmptyCredentials" finished-at="2025-01-02T15:50:59 SEČ" duration-ms="521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_loginWithEmptyCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.parabank.parasoft.testCases.LoginTest@34123d65]" started-at="2025-01-02T15:50:59 SEČ" name="tearDown" finished-at="2025-01-02T15:50:59 SEČ" duration-ms="108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.parabank.parasoft.testCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
